### ISSUE TITLE
how does the app.conf , server.pyj and client works ?

### ISSUE THREAD

**Issue by kalmenchia** [rafi16jan/rapyd-framework#2]
Hi, i managed to run 
    rm -f */*.pyj-cached && node ./node_modules/.bin/rapydscript -p modules -x server.pyj
but i am confused about the app.conf , where does it points to , what i mean is that

> master_password = neverfindout
> default_url = http://localhost
> port = 8079
> client_db = 'local_client_db'
> server_db = 'local_server_db'

when uses this app.conf , it does not seems to work ? i have a local odoo v10 instance 
at http://localhost:8069 , but after i run this , it replaced and took over the port ,

i have specified the above as port 8079 , but it still show Running on port 8069 , hard code
somewhere ? how to actually run it properly and test it ?

thanks.

**Comment by rafi16jan** [comment]
Sorry I doesn't have time to update the README.md. App.conf is for server.js, to run it, execute `node server.js` or if you want to clear cache `node server.js --clear-cache`

Thanks for trying my framework, I appreciate it

**Comment by rafi16jan** [comment]
@kalmenchia please git pull or update your files with a new one since I made some fix

**Comment by kalmenchia** [comment]
thanks , manage to connect without need to start odoo instance so can i check with you this framework is standalone without need to work with Odoo right ?

**Comment by rafi16jan** [comment]
Yes this is a separate project that aren't depending on each other. Are you experiencing another problems? Feel free to share it

**Comment by kalmenchia** [comment]
Thanks for the answer , appreciate your work a lot, i am interested in develop own framework too perhaps can contribute somehow , at the moment , my choice is vuejs + vuex + F7 + firebase (offline db)  .

**Comment by rafi16jan** [comment]
Ok, closing the issue
